package world

// VoxelVertex is the GPU vertex layout. It must match the vertex attributes
// declared when the renderer builds the graphics pipeline:
//
//   - location 0: FLOAT3       position (world space)        offset  0
//   - location 1: FLOAT2       texture coordinate (atlas UV) offset 12
//   - location 2: UBYTE4_NORM  per-vertex colour             offset 20
//
// The shader (TexturedQuadColorWithMatrix.vert) expects a float4 position and
// float4 colour; SDL_gpu fills the missing component with 1.0 for a FLOAT3
// attribute and expands UBYTE4_NORM to a normalised float4 automatically.
//
// The colour channel does double duty: for plain blocks it carries a grayscale
// face-shade value (fake directional lighting); for tinted faces (grass top,
// grass side overlay) it carries shade × biome tint, which the fragment shader
// multiplies with the grayscale texture to produce a biome-coloured result.
type VoxelVertex struct {
	X, Y, Z   float32
	U, V      float32
	R, G, B, A uint8
}

// ChunkMeshData is the CPU-side result of meshing a chunk. It has two layers:
//
//   - Vertices/Indices: the opaque base layer (every visible face).
//   - Overlay/OverlayIdx: the tinted, alpha-blended layer (grass side overlays).
//
// The renderer uploads each layer into its own GPU buffers and draws them with
// separate pipelines. Vertices are stored in world space so a single
// view-projection uniform can be shared across every chunk draw.
type ChunkMeshData struct {
	Vertices   []VoxelVertex
	Indices    []uint32
	Overlay    []VoxelVertex
	OverlayIdx []uint32
}

// AtlasUVProvider maps a tile index to its UV rectangle inside the block
// texture atlas. The renderer's atlas implements this.
type AtlasUVProvider interface {
	// TileUV returns the min and max UV coordinates (u0,v0)-(u1,v1) for tile.
	TileUV(tile uint8) (u0, v0, u1, v1 float32)
}

// BlockSampler returns the block at a world-space block coordinate, crossing
// chunk boundaries. The world provides this so the mesher can query neighbour
// blocks that live in adjacent chunks.
type BlockSampler func(wx, wy, wz int32) BlockID

// BiomeSampler returns the biome at a world-space column. The mesher uses it to
// look up the grass tint for grass-block faces.
type BiomeSampler func(wx, wz int32) BiomeID

// faceCorners gives the four corner offsets (relative to a block's min corner)
// for each face, ordered counter-clockwise as seen from outside so that
// back-face culling with a CCW front face removes the hidden side.
//
// Corner order is: bottom-left, bottom-right, top-right, top-left.
var faceCorners = [NumFaces][4][3]int32{
	{ // +X
		{1, 0, 1}, {1, 0, 0}, {1, 1, 0}, {1, 1, 1},
	},
	{ // -X
		{0, 0, 0}, {0, 0, 1}, {0, 1, 1}, {0, 1, 0},
	},
	{ // +Y (top)
		{0, 1, 1}, {1, 1, 1}, {1, 1, 0}, {0, 1, 0},
	},
	{ // -Y (bottom)
		{0, 0, 0}, {1, 0, 0}, {1, 0, 1}, {0, 0, 1},
	},
	{ // +Z (south)
		{0, 0, 1}, {1, 0, 1}, {1, 1, 1}, {0, 1, 1},
	},
	{ // -Z (north)
		{1, 0, 0}, {0, 0, 0}, {0, 1, 0}, {1, 1, 0},
	},
}

// faceUV maps each of the four corners (BL, BR, TR, TL) to a [0..1] UV inside
// the tile. V increases downward because SDL_gpu textures have their origin at
// the top-left, so the bottom edge of a face maps to v1 (the lower pixel rows).
var faceUV = [4][2]float32{
	{0, 1}, // bottom-left
	{1, 1}, // bottom-right
	{1, 0}, // top-right
	{0, 0}, // top-left
}

// faceShade is a per-face brightness used to fake directional lighting. Top is
// brightest, bottom darkest, and the four sides sit between so cubes read as
// solid 3D objects even under flat ambient lighting.
var faceShade = [NumFaces]uint8{
	196, // +X
	196, // -X
	255, // +Y (top)
	130, // -Y (bottom)
	168, // +Z
	168, // -Z
}

// shouldDrawFace decides whether a face of block b is visible given the
// neighbour nb on that side. A face is hidden when the neighbour is opaque, or
// when the neighbour is the same transparent block type (so two glass blocks
// don't render their shared internal faces).
func shouldDrawFace(b, nb BlockID) bool {
	if b.IsAir() {
		return false
	}
	if nb.IsOpaque() {
		return false
	}
	if nb == b {
		return false
	}
	return true
}

// BuildChunkMesh extracts the visible surface mesh of a chunk.
//
// The mesh is generated by visiting every solid block and, for each of its six
// faces, emitting a quad unless the neighbouring block occludes it (face
// culling). Grass blocks get special treatment: the top face is tinted by the
// column's biome colour, and each side face is emitted as two layers — an
// opaque dirt base plus a tinted, alpha-blended grass overlay. Vertices are
// emitted in world space so the renderer can share one view-projection matrix
// across all chunks.
func BuildChunkMesh(c *Chunk, sample BlockSampler, biomeSample BiomeSampler, atlas AtlasUVProvider) ChunkMeshData {
	ox, oy, oz := c.Pos.WorldOrigin()

	data := ChunkMeshData{
		Vertices:   make([]VoxelVertex, 0, 8192),
		Indices:    make([]uint32, 0, 12288),
		Overlay:    make([]VoxelVertex, 0, 2048),
		OverlayIdx: make([]uint32, 0, 3072),
	}

	for ly := 0; ly < ChunkSize; ly++ {
		for lz := 0; lz < ChunkSize; lz++ {
			for lx := 0; lx < ChunkSize; lx++ {
				b := c.GetLocal(lx, ly, lz)
				if b.IsAir() {
					continue
				}
				wx, wy, wz := ox+int32(lx), oy+int32(ly), oz+int32(lz)
				emitBlockFaces(&data, b, wx, wy, wz, sample, biomeSample, atlas)
			}
		}
	}

	return data
}

// emitBlockFaces emits every visible face of a single block into the mesh.
func emitBlockFaces(data *ChunkMeshData, b BlockID, wx, wy, wz int32,
	sample BlockSampler, biomeSample BiomeSampler, atlas AtlasUVProvider) {

	grass := b == Grass
	var tint [3]float32
	if grass {
		tint = GrassTint(biomeSample(wx, wz))
	}

	for face := 0; face < NumFaces; face++ {
		off := faceOffsets[face]
		nb := sample(wx+off[0], wy+off[1], wz+off[2])
		if !shouldDrawFace(b, nb) {
			continue
		}
		shade := faceShade[face]

		if !grass {
			emitQuad(&data.Vertices, &data.Indices, b.Tile(face), face, wx, wy, wz, atlas, shadeColor(shade))
			continue
		}

		// Grass: top is tinted, bottom is plain dirt, sides are base + overlay.
		switch face {
		case FacePosY:
			emitQuad(&data.Vertices, &data.Indices, tileGrassTop, face, wx, wy, wz, atlas, tintColor(shade, tint))
		case FaceNegY:
			emitQuad(&data.Vertices, &data.Indices, tileDirt, face, wx, wy, wz, atlas, shadeColor(shade))
		default:
			emitQuad(&data.Vertices, &data.Indices, tileGrassSide, face, wx, wy, wz, atlas, shadeColor(shade))
			emitQuad(&data.Overlay, &data.OverlayIdx, tileGrassSideOverlay, face, wx, wy, wz, atlas, tintColor(shade, tint))
		}
	}
}

// emitQuad appends one quad (four vertices, two triangles) for the given face
// of the block at world coordinate (wx,wy,wz), using the given atlas tile and
// vertex colour, into the supplied vertex/index slices.
func emitQuad(verts *[]VoxelVertex, idx *[]uint32, tile uint8, face int,
	wx, wy, wz int32, atlas AtlasUVProvider, color [4]uint8) {

	u0, v0, u1, v1 := atlas.TileUV(tile)
	du := u1 - u0
	dv := v1 - v0

	corners := faceCorners[face]
	base := uint32(len(*verts))

	for i := 0; i < 4; i++ {
		co := corners[i]
		uv := faceUV[i]
		*verts = append(*verts, VoxelVertex{
			X: float32(wx) + float32(co[0]),
			Y: float32(wy) + float32(co[1]),
			Z: float32(wz) + float32(co[2]),
			U: u0 + uv[0]*du,
			V: v0 + uv[1]*dv,
			R: color[0], G: color[1], B: color[2], A: color[3],
		})
	}

	// Two triangles: (0,1,2) and (0,2,3), CCW from outside.
	*idx = append(*idx,
		base, base+1, base+2,
		base, base+2, base+3,
	)
}

// shadeColor returns a grayscale vertex colour for a plain (untinted) face.
func shadeColor(shade uint8) [4]uint8 {
	return [4]uint8{shade, shade, shade, 255}
}

// tintColor returns a vertex colour for a biome-tinted face: the biome grass
// tint multiplied by the per-face shade, so tinted faces still get directional
// darkening. The fragment shader multiplies this by the grayscale texture.
func tintColor(shade uint8, tint [3]float32) [4]uint8 {
	s := float32(shade)
	return [4]uint8{
		clamp8(s * tint[0]),
		clamp8(s * tint[1]),
		clamp8(s * tint[2]),
		255,
	}
}

// clamp8 clamps a float32 to the [0,255] byte range.
func clamp8(v float32) uint8 {
	if v >= 255 {
		return 255
	}
	if v <= 0 {
		return 0
	}
	return uint8(v)
}
