package world

// VoxelVertex is the GPU vertex layout. It must match the vertex attributes
// declared when the renderer builds the graphics pipeline:
//
//   - location 0: FLOAT3       position (world space)        offset  0
//   - location 1: FLOAT2       texture coordinate (atlas UV) offset 12
//   - location 2: UBYTE4_NORM  per-vertex colour shade       offset 20
//
// The shader (TexturedQuadColorWithMatrix.vert) expects a float4 position and
// float4 colour; SDL_gpu fills the missing component with 1.0 for a FLOAT3
// attribute and expands UBYTE4_NORM to a normalised float4 automatically.
type VoxelVertex struct {
	X, Y, Z float32
	U, V    float32
	R, G, B, A uint8
}

// ChunkMeshData is the CPU-side result of meshing a chunk. The renderer uploads
// these slices into GPU buffers. Vertices are stored in world space so that a
// single view-projection uniform can be shared across every chunk draw.
type ChunkMeshData struct {
	Vertices []VoxelVertex
	Indices  []uint32
}

// AtlasUVProvider maps a tile index to its (already inset) UV rectangle inside
// the block texture atlas. The renderer's atlas implements this.
type AtlasUVProvider interface {
	// TileUV returns the min and max UV coordinates (u0,v0)-(u1,v1) for tile,
	// with a half-texel inset applied to avoid bleeding between adjacent tiles.
	TileUV(tile uint8) (u0, v0, u1, v1 float32)
}

// BlockSampler returns the block at a world-space block coordinate, crossing
// chunk boundaries. The world provides this so the mesher can query neighbour
// blocks that live in adjacent chunks.
type BlockSampler func(wx, wy, wz int32) BlockID

// faceCorners gives the four corner offsets (relative to a block's min corner)
// for each face, ordered counter-clockwise as seen from outside so that
// back-face culling with a CCW front face removes the hidden side.
//
// Corner order is: bottom-left, bottom-right, top-right, top-left.
var faceCorners = [NumFaces][4][3]int32{
	{ // +X
		{1, 0, 1}, {1, 0, 0}, {1, 1, 0}, {1, 1, 1},
	},
	{ // -X
		{0, 0, 0}, {0, 0, 1}, {0, 1, 1}, {0, 1, 0},
	},
	{ // +Y (top)
		{0, 1, 1}, {1, 1, 1}, {1, 1, 0}, {0, 1, 0},
	},
	{ // -Y (bottom)
		{0, 0, 0}, {1, 0, 0}, {1, 0, 1}, {0, 0, 1},
	},
	{ // +Z (south)
		{0, 0, 1}, {1, 0, 1}, {1, 1, 1}, {0, 1, 1},
	},
	{ // -Z (north)
		{1, 0, 0}, {0, 0, 0}, {0, 1, 0}, {1, 1, 0},
	},
}

// faceUV maps each of the four corners (BL, BR, TR, TL) to a [0..1] UV inside
// the tile. V increases downward because SDL_gpu textures have their origin at
// the top-left, so the bottom edge of a face maps to v1 (the lower pixel rows).
var faceUV = [4][2]float32{
	{0, 1}, // bottom-left
	{1, 1}, // bottom-right
	{1, 0}, // top-right
	{0, 0}, // top-left
}

// faceShade is a per-face brightness used to fake directional lighting. Top is
// brightest, bottom darkest, and the four sides sit between so cubes read as
// solid 3D objects even under flat ambient lighting.
var faceShade = [NumFaces]uint8{
	196, // +X
	196, // -X
	255, // +Y (top)
	130, // -Y (bottom)
	168, // +Z
	168, // -Z
}

// shouldDrawFace decides whether a face of block b is visible given the
// neighbour nb on that side. A face is hidden when the neighbour is opaque, or
// when the neighbour is the same transparent block type (so two glass blocks
// don't render their shared internal faces).
func shouldDrawFace(b, nb BlockID) bool {
	if b.IsAir() {
		return false
	}
	if nb.IsOpaque() {
		return false
	}
	if nb == b {
		return false
	}
	return true
}

// BuildChunkMesh extracts the visible surface mesh of a chunk.
//
// The mesh is generated by visiting every solid block and, for each of its six
// faces, emitting a quad unless the neighbouring block occludes it (face
// culling). Vertices are emitted in world space so the renderer can share one
// view-projection matrix across all chunks.
func BuildChunkMesh(c *Chunk, sample BlockSampler, atlas AtlasUVProvider) ChunkMeshData {
	ox, oy, oz := c.Pos.WorldOrigin()

	// Pre-allocate with a generous capacity; a typical surface chunk has far
	// fewer faces than the worst case, and append grows geometrically.
	data := ChunkMeshData{
		Vertices: make([]VoxelVertex, 0, 8192),
		Indices:  make([]uint32, 0, 12288),
	}

	for ly := 0; ly < ChunkSize; ly++ {
		for lz := 0; lz < ChunkSize; lz++ {
			for lx := 0; lx < ChunkSize; lx++ {
				b := c.GetLocal(lx, ly, lz)
				if b.IsAir() {
					continue
				}
				wx, wy, wz := ox+int32(lx), oy+int32(ly), oz+int32(lz)
				for face := 0; face < NumFaces; face++ {
					off := faceOffsets[face]
					nb := sample(wx+off[0], wy+off[1], wz+off[2])
					if !shouldDrawFace(b, nb) {
						continue
					}
					emitFace(&data, b, face, wx, wy, wz, atlas)
				}
			}
		}
	}

	return data
}

// emitFace appends one quad (four vertices, two triangles) for the given face
// of the block at world coordinate (wx,wy,wz).
func emitFace(data *ChunkMeshData, b BlockID, face int, wx, wy, wz int32, atlas AtlasUVProvider) {
	tile := b.Tile(face)
	u0, v0, u1, v1 := atlas.TileUV(tile)
	du := u1 - u0
	dv := v1 - v0

	corners := faceCorners[face]
	shade := faceShade[face]
	base := uint32(len(data.Vertices))

	for i := 0; i < 4; i++ {
		co := corners[i]
		uv := faceUV[i]
		data.Vertices = append(data.Vertices, VoxelVertex{
			X: float32(wx) + float32(co[0]),
			Y: float32(wy) + float32(co[1]),
			Z: float32(wz) + float32(co[2]),
			U: u0 + uv[0]*du,
			V: v0 + uv[1]*dv,
			R: shade, G: shade, B: shade, A: 255,
		})
	}

	// Two triangles: (0,1,2) and (0,2,3), CCW from outside.
	data.Indices = append(data.Indices,
		base, base+1, base+2,
		base, base+2, base+3,
	)
}
